### ISSUE TITLE
How to set the popup's background color?

### ISSUE THREAD

**Issue by Sasino97** [BytexDigital/BytexDigital.Blazor.Components.CookieConsent#38]
I'm using the following CSS:
```css
.cc-isolation-container * {
    --cc-font-family: "Noto Sans", "Noto Naskh Arabic", "Noto Sans TC", "Noto Sans SC", "sans-serif";
    --cc-color-accent: rgb(255, 134, 55);
    --cc-color-accent-dark: rgb(245, 124, 45);
    --cc-color-secondary: rgb(0, 124, 234);
    --cc-color-secondary-dark: rgb(0, 114, 224);
    --cc-color-link: rgb(255, 134, 55);
    --cc-color-link-highlight: rgb(255, 134, 55);
    --cc-color-text: rgb(230, 230, 230);
    --cc-color-switch-active: rgb(33, 35, 40);
    --cc-color-modal-background: rgba(33, 35, 40, 0.15);
}
```
But there's no option to set the background color, so I can't set it.

![Image](https://github.com/user-attachments/assets/a4ebc7a3-d028-43c9-8bb0-8918a6200ea8)

My website is dark, so I don't like to be forced to have a light cookie popup.
